#FROM nginx
FROM lifesboy/landnews-data

#RUN apt update\
#    && apt install lsyncd\
#    && ln -s /usr/bin/lsyncd /sbin
ADD ./lsyncd.conf.lua /etc/lsyncd/lsyncd.conf.lua

CMD ["lsyncd", "-direct", "/backup", "/volumes", "-nodaemon"]
#CMD ["lsyncd && nginx", "-g", "daemon off;"]